# Generated by Django 4.2.30 on 2026-04-14 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('total_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3')])),
                ('text', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['part', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_fluency', models.FloatField(blank=True, null=True)),
                ('feedback_vocabulary', models.FloatField(blank=True, null=True)),
                ('feedback_grammar', models.FloatField(blank=True, null=True)),
                ('feedback_pronunciation', models.FloatField(blank=True, null=True)),
                ('feedback_overall', models.FloatField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('feedback_strengths', models.TextField(blank=True)),
                ('feedback_improvements', models.TextField(blank=True)),
                ('model_answer', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speaking.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='speaking.practicesession')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
    ]
