QUESTIONS = [
    # ─── PART 1 (20 questions) ───────────────────────────────────────────────
    {'part': 1, 'order': 1,  'topic': 'Introduction', 'text': "Can you tell me your full name and where you're from?"},
    {'part': 1, 'order': 2,  'topic': 'Home',         'text': "Do you live in a house or an apartment? Do you like it?"},
    {'part': 1, 'order': 3,  'topic': 'Work/Study',   'text': "Are you currently working or studying? What do you do?"},
    {'part': 1, 'order': 4,  'topic': 'Hometown',     'text': "What do you like most about your hometown?"},
    {'part': 1, 'order': 5,  'topic': 'Free Time',    'text': "What do you enjoy doing in your free time?"},
    {'part': 1, 'order': 6,  'topic': 'Music',        'text': "Do you enjoy listening to music? What kind of music do you like?"},
    {'part': 1, 'order': 7,  'topic': 'Food',         'text': "What is your favourite food? How often do you eat it?"},
    {'part': 1, 'order': 8,  'topic': 'Travel',       'text': "Do you like travelling? Where have you been recently?"},
    {'part': 1, 'order': 9,  'topic': 'Sports',       'text': "Do you play any sports or do any physical exercise?"},
    {'part': 1, 'order': 10, 'topic': 'Reading',      'text': "Do you enjoy reading? What types of books do you read?"},
    {'part': 1, 'order': 11, 'topic': 'Technology',   'text': "How important is technology in your daily life?"},
    {'part': 1, 'order': 12, 'topic': 'Friends',      'text': "How do you usually spend time with your friends?"},
    {'part': 1, 'order': 13, 'topic': 'Weather',      'text': "What kind of weather do you prefer? Why?"},
    {'part': 1, 'order': 14, 'topic': 'Shopping',     'text': "Do you enjoy shopping? Do you prefer online or in-store shopping?"},
    {'part': 1, 'order': 15, 'topic': 'Morning',      'text': "Are you a morning person or a night person? What is your morning routine?"},
    {'part': 1, 'order': 16, 'topic': 'Cooking',      'text': "Do you enjoy cooking? What is your signature dish?"},
    {'part': 1, 'order': 17, 'topic': 'Social Media', 'text': "How much time do you spend on social media every day?"},
    {'part': 1, 'order': 18, 'topic': 'Nature',       'text': "Do you prefer the city or the countryside? Why?"},
    {'part': 1, 'order': 19, 'topic': 'Childhood',    'text': "What did you enjoy doing most as a child?"},
    {'part': 1, 'order': 20, 'topic': 'Future',       'text': "Where do you see yourself in five years?"},

    # ─── PART 2 (20 questions / cue cards) ──────────────────────────────────
    {'part': 2, 'order': 1,  'topic': 'Person',       'text': "Describe a person who has had a great influence on your life. You should say: who this person is, how you know them, what qualities they have, and explain why they have influenced you so much."},
    {'part': 2, 'order': 2,  'topic': 'Place',        'text': "Describe a place you have visited that you particularly enjoyed. You should say: where it is, when you went there, what you did there, and explain why you enjoyed it so much."},
    {'part': 2, 'order': 3,  'topic': 'Object',       'text': "Describe an object that is very important to you. You should say: what it is, how long you have had it, what you use it for, and explain why it is so important to you."},
    {'part': 2, 'order': 4,  'topic': 'Event',        'text': "Describe an event that made you very happy. You should say: what the event was, when it happened, who was there, and explain why it made you so happy."},
    {'part': 2, 'order': 5,  'topic': 'Achievement',  'text': "Describe something you achieved that you are proud of. You should say: what you achieved, when you achieved it, how you achieved it, and explain why you are proud of it."},
    {'part': 2, 'order': 6,  'topic': 'Book/Film',    'text': "Describe a book or film that had a strong impact on you. You should say: what the book or film was about, when you read or watched it, who recommended it, and explain why it had such a strong impact on you."},
    {'part': 2, 'order': 7,  'topic': 'Journey',      'text': "Describe an interesting journey you have taken. You should say: where you went, how you travelled, who you went with, and explain what made the journey interesting."},
    {'part': 2, 'order': 8,  'topic': 'Skill',        'text': "Describe a skill you would like to learn. You should say: what the skill is, why you want to learn it, how you would learn it, and explain how it would benefit your life."},
    {'part': 2, 'order': 9,  'topic': 'Tradition',    'text': "Describe a tradition in your culture that you find interesting. You should say: what the tradition is, when it takes place, how people celebrate it, and explain why you find it interesting."},
    {'part': 2, 'order': 10, 'topic': 'Problem',      'text': "Describe a time when you solved a difficult problem. You should say: what the problem was, when it happened, how you solved it, and explain how you felt after solving it."},
    {'part': 2, 'order': 11, 'topic': 'Ambition',     'text': "Describe something you want to do in the future. You should say: what it is, why you want to do it, how you plan to do it, and explain how it would change your life."},
    {'part': 2, 'order': 12, 'topic': 'Meal',         'text': "Describe a memorable meal you have had. You should say: where you had it, who you were with, what you ate, and explain why it was so memorable."},
    {'part': 2, 'order': 13, 'topic': 'Teacher',      'text': "Describe a teacher who inspired you. You should say: who this teacher was, what subject they taught, what they did that inspired you, and explain how they influenced your life."},
    {'part': 2, 'order': 14, 'topic': 'News',         'text': "Describe an interesting news story you heard recently. You should say: what the story was about, where you heard it, who was involved, and explain why you found it interesting."},
    {'part': 2, 'order': 15, 'topic': 'Sport',        'text': "Describe a sport or physical activity you enjoy. You should say: what it is, how often you do it, who you do it with, and explain why you enjoy it."},
    {'part': 2, 'order': 16, 'topic': 'Gift',         'text': "Describe a gift you received that meant a lot to you. You should say: what the gift was, who gave it to you, when you received it, and explain why it meant so much."},
    {'part': 2, 'order': 17, 'topic': 'Technology',   'text': "Describe a piece of technology you use every day. You should say: what it is, how you use it, how long you have had it, and explain why it is important to you."},
    {'part': 2, 'order': 18, 'topic': 'Mistake',      'text': "Describe a mistake you made and what you learned from it. You should say: what the mistake was, when it happened, what consequences it had, and explain what you learned from it."},
    {'part': 2, 'order': 19, 'topic': 'Hobby',        'text': "Describe a hobby you have had for a long time. You should say: what the hobby is, how you started it, how often you do it, and explain why you have continued with it."},
    {'part': 2, 'order': 20, 'topic': 'Dream',        'text': "Describe your dream job. You should say: what the job is, what it involves, what skills are needed, and explain why it is your dream job."},

    # ─── PART 3 (20 questions) ───────────────────────────────────────────────
    {'part': 3, 'order': 1,  'topic': 'Education',    'text': "How has the education system in your country changed over the past few decades?"},
    {'part': 3, 'order': 2,  'topic': 'Technology',   'text': "Do you think technology has had more positive or negative effects on society? Why?"},
    {'part': 3, 'order': 3,  'topic': 'Environment',  'text': "What do you think are the most serious environmental problems facing the world today?"},
    {'part': 3, 'order': 4,  'topic': 'Work',         'text': "How do you think the nature of work will change in the future with the rise of AI and automation?"},
    {'part': 3, 'order': 5,  'topic': 'Globalisation','text': "What are the advantages and disadvantages of globalisation for developing countries?"},
    {'part': 3, 'order': 6,  'topic': 'Media',        'text': "How has social media changed the way people communicate and form relationships?"},
    {'part': 3, 'order': 7,  'topic': 'Health',       'text': "What do you think governments should do to encourage healthier lifestyles among citizens?"},
    {'part': 3, 'order': 8,  'topic': 'Culture',      'text': "Do you think it is important for younger generations to preserve traditional cultural practices? Why?"},
    {'part': 3, 'order': 9,  'topic': 'Economy',      'text': "What are the main causes of the gap between rich and poor in modern societies?"},
    {'part': 3, 'order': 10, 'topic': 'Cities',       'text': "What are the main challenges that large cities face today, and how can they be addressed?"},
    {'part': 3, 'order': 11, 'topic': 'Family',       'text': "How have family structures and roles changed in your country compared to previous generations?"},
    {'part': 3, 'order': 12, 'topic': 'Crime',        'text': "What do you think are the root causes of crime in society, and how can they be tackled?"},
    {'part': 3, 'order': 13, 'topic': 'Tourism',      'text': "What are the positive and negative impacts of tourism on local communities?"},
    {'part': 3, 'order': 14, 'topic': 'Food',         'text': "How have people's eating habits changed in recent years, and what has caused these changes?"},
    {'part': 3, 'order': 15, 'topic': 'Science',      'text': "How important is scientific research for the progress of humanity? Should it be government-funded?"},
    {'part': 3, 'order': 16, 'topic': 'Leadership',   'text': "What qualities do you think make a great leader in today's world?"},
    {'part': 3, 'order': 17, 'topic': 'Gender',       'text': "Do you think men and women have equal opportunities in the workplace today? Why or why not?"},
    {'part': 3, 'order': 18, 'topic': 'Space',        'text': "Do you think space exploration is worth the enormous costs involved? Why or why not?"},
    {'part': 3, 'order': 19, 'topic': 'Youth',        'text': "What challenges do young people face today that previous generations did not have to deal with?"},
    {'part': 3, 'order': 20, 'topic': 'Language',     'text': "Do you think the dominance of English as a global language is a positive or negative development?"},
]
